import { LabelReference } from '../models/label.model';

/** Figma `26002:181586` / `27302:169958` — built-in label reference catalog (60 rows). */
export const SYSTEM_LABEL_REFERENCES: Omit<LabelReference, 'enabled'>[] = [
  {
    id: 'label-store-order-number',
    name: 'Store Order Number',
    description:
      'Unique order identifier generated by the merchant’s store for tracking and customer reference.',
    isSystem: true,
  },
  {
    id: 'label-platform-order-id',
    name: 'Platform Order ID',
    description: 'Order identifier assigned by the connected sales platform or marketplace.',
    isSystem: true,
  },
  {
    id: 'label-shiplo-order-id',
    name: 'Shiplo Order ID',
    description:
      'Internal order identifier generated within Shiplo for tracking and system-level operations.',
    isSystem: true,
  },
  {
    id: 'label-tracking-number',
    name: 'Tracking Number',
    description: 'Carrier tracking number assigned after the label is purchased.',
    isSystem: true,
  },
  {
    id: 'label-shipment',
    name: 'Shipment',
    description: 'Shiplo shipment identifier for the outbound package.',
    isSystem: true,
  },
  {
    id: 'label-package-carton-id',
    name: 'Package ID / Carton ID',
    description: 'Identifier for the individual package or carton within a shipment.',
    isSystem: true,
  },
  {
    id: 'label-package-count',
    name: 'Package Count',
    description: 'Total number of packages included in the shipment.',
    isSystem: true,
  },
  {
    id: 'label-customer-name',
    name: 'Customer Name',
    description: 'Recipient name from the order shipping address.',
    isSystem: true,
  },
  {
    id: 'label-customer-email',
    name: 'Customer Email',
    description: 'Customer email address associated with the order.',
    isSystem: true,
  },
  {
    id: 'label-customer-phone',
    name: 'Customer Phone',
    description: 'Customer phone number from the order or shipping profile.',
    isSystem: true,
  },
  {
    id: 'label-shipping-postal',
    name: 'Shipping ZIP / Postal Code',
    description: 'Destination postal or ZIP code for the shipment.',
    isSystem: true,
  },
  {
    id: 'label-destination-city-state',
    name: 'Destination City / State',
    description: 'Destination city and state or province for the shipment.',
    isSystem: true,
  },
  {
    id: 'label-store-brand-name',
    name: 'Store Name / Brand Name',
    description: 'Merchant store or brand name shown on customer-facing materials.',
    isSystem: true,
  },
  {
    id: 'label-sales-channel',
    name: 'Sales Channel',
    description: 'Channel the order originated from, such as web, retail, or marketplace.',
    isSystem: true,
  },
  {
    id: 'label-marketplace-order-id',
    name: 'Marketplace Order ID',
    description: 'External marketplace order identifier when sold through a connector.',
    isSystem: true,
  },
  {
    id: 'label-fulfillment-method',
    name: 'Fulfillment Method',
    description: 'Fulfillment strategy used for the order, such as ship-from-store or warehouse.',
    isSystem: true,
  },
  {
    id: 'label-warehouse-code',
    name: 'Warehouse Code',
    description: 'Code for the warehouse or fulfillment location shipping the order.',
    isSystem: true,
  },
  {
    id: 'label-location-store-id',
    name: 'Location (Store ID)',
    description: 'Retail or fulfillment location identifier tied to the shipment.',
    isSystem: true,
  },
  {
    id: 'label-pick-batch-wave-id',
    name: 'Pick Batch / Wave ID',
    description: 'Warehouse pick batch or wave identifier used during fulfillment.',
    isSystem: true,
  },
  {
    id: 'label-pick-list-id',
    name: 'Pick List ID',
    description: 'Identifier for the pick list generated for this shipment.',
    isSystem: true,
  },
  {
    id: 'label-packer-station-id',
    name: 'Packer ID / Station ID',
    description: 'Packer or packing station that completed the shipment.',
    isSystem: true,
  },
  {
    id: 'label-packing-slip-number',
    name: 'Packing Slip Number',
    description: 'Packing slip reference number included with the shipment.',
    isSystem: true,
  },
  {
    id: 'label-invoice-number',
    name: 'Invoice Number',
    description: 'Invoice or billing reference associated with the order.',
    isSystem: true,
  },
  {
    id: 'label-payment-status',
    name: 'Payment Status',
    description: 'Payment state for the order, such as paid, pending, or refunded.',
    isSystem: true,
  },
  {
    id: 'label-fraud-review-flag',
    name: 'Fraud Review Flag',
    description: 'Indicates whether the order is flagged for fraud review.',
    isSystem: true,
  },
  {
    id: 'label-gift-flag',
    name: 'Gift Flag',
    description: 'Marks the order as a gift shipment for packing and labeling.',
    isSystem: true,
  },
  {
    id: 'label-gift-message-id',
    name: 'Gift Message ID',
    description: 'Reference to the gift message attached to the order.',
    isSystem: true,
  },
  {
    id: 'label-subscription-id',
    name: 'Subscription ID',
    description: 'Subscription identifier when the order is part of a recurring program.',
    isSystem: true,
  },
  {
    id: 'label-subscription-cycle',
    name: 'Subscription Cycle',
    description: 'Billing or fulfillment cycle number for subscription orders.',
    isSystem: true,
  },
  {
    id: 'label-order-type',
    name: 'Order Type',
    description: 'Classification of the order, such as standard, exchange, or replacement.',
    isSystem: true,
  },
  {
    id: 'label-rma-number',
    name: 'RMA Number',
    description: 'Return merchandise authorization number for return shipments.',
    isSystem: true,
  },
  {
    id: 'label-exchange-case-id',
    name: 'Exchange Case ID',
    description: 'Identifier for an exchange case tied to the order.',
    isSystem: true,
  },
  {
    id: 'label-replacement-order',
    name: 'Replacement Order',
    description: 'Reference to a replacement order linked to the original.',
    isSystem: true,
  },
  {
    id: 'label-return-reason-code',
    name: 'Return Reason Code',
    description: 'Code indicating why the item is being returned.',
    isSystem: true,
  },
  {
    id: 'label-return-status-code',
    name: 'Return Status Code',
    description: 'Current status code for the return workflow.',
    isSystem: true,
  },
  {
    id: 'label-promo-code',
    name: 'Promo Code',
    description: 'Promotional or discount code applied to the order.',
    isSystem: true,
  },
  {
    id: 'label-campaign-utm-tag',
    name: 'Campaign / UTM Tag',
    description: 'Marketing campaign or UTM tracking tag from the order source.',
    isSystem: true,
  },
  {
    id: 'label-sla-delivery-promise',
    name: 'SLA / Delivery Promise',
    description: 'Committed delivery date or service level agreement window.',
    isSystem: true,
  },
  {
    id: 'label-shipping-method-store',
    name: 'Shipping Method (Store)',
    description: 'Shipping method selected at checkout in the store.',
    isSystem: true,
  },
  {
    id: 'label-carrier-service',
    name: 'Carrier Service',
    description: 'Carrier service level used for the shipment label.',
    isSystem: true,
  },
  {
    id: 'label-rate-rule-automation',
    name: 'Rate Rule / Automation',
    description: 'Automation or rate rule that selected the shipping option.',
    isSystem: true,
  },
  {
    id: 'label-handling-tag',
    name: 'Handling Tag',
    description: 'Special handling instructions tag for the package.',
    isSystem: true,
  },
  {
    id: 'label-temperature-service',
    name: 'Temperature Service',
    description: 'Temperature-controlled service indicator for the shipment.',
    isSystem: true,
  },
  {
    id: 'label-lithium-battery-flag',
    name: 'Lithium Battery Flag',
    description: 'Indicates whether the shipment contains lithium batteries.',
    isSystem: true,
  },
  {
    id: 'label-customs-hs-code',
    name: 'Customs Code (HS Code)',
    description: 'Harmonized System code for customs clearance.',
    isSystem: true,
  },
  {
    id: 'label-ms-code-primary',
    name: 'MS Code (Primary)',
    description: 'Primary merchant stock-keeping code for the shipment.',
    isSystem: true,
  },
  {
    id: 'label-default-item-description',
    name: 'Default Item Description',
    description: 'Default product description printed on the label.',
    isSystem: true,
  },
  {
    id: 'label-vat-oss-flag',
    name: 'VAT/OSS Flag',
    description: 'VAT or One Stop Shop tax scheme indicator for EU orders.',
    isSystem: true,
  },
  {
    id: 'label-cart-order-notes',
    name: 'Cart Notes / Order Notes',
    description: 'Customer-facing notes from the cart or order.',
    isSystem: true,
  },
  {
    id: 'label-internal-notes-tag',
    name: 'Internal Notes Tag',
    description: 'Internal-only note tag for warehouse or ops staff.',
    isSystem: true,
  },
  {
    id: 'label-customer-segment',
    name: 'Customer Segment',
    description: 'Customer segment or cohort classification.',
    isSystem: true,
  },
  {
    id: 'label-loyalty-tier',
    name: 'Loyalty Tier',
    description: 'Customer loyalty tier or membership level.',
    isSystem: true,
  },
  {
    id: 'label-support-ticket-id',
    name: 'Support Ticket ID',
    description: 'Support ticket reference linked to the order.',
    isSystem: true,
  },
  {
    id: 'label-bundle-kit-id',
    name: 'Bundle ID / Kit ID',
    description: 'Identifier for a product bundle or kit in the order.',
    isSystem: true,
  },
  {
    id: 'label-primary-sku',
    name: 'Primary SKU',
    description: 'Primary stock-keeping unit for the shipment contents.',
    isSystem: true,
  },
  {
    id: 'label-sku-summary',
    name: 'SKU Summary',
    description: 'Summary list or count of SKUs in the shipment.',
    isSystem: true,
  },
  {
    id: 'label-line-item-count',
    name: 'Line Item Count',
    description: 'Total number of line items in the order.',
    isSystem: true,
  },
  {
    id: 'label-weight-class',
    name: 'Weight Class',
    description: 'Weight class or category used for carrier rating.',
    isSystem: true,
  },
  {
    id: 'label-dimension-class',
    name: 'Dimension Class',
    description: 'Dimensional weight class for carrier rating.',
    isSystem: true,
  },
  {
    id: 'label-box-type',
    name: 'Box Type',
    description: 'Packaging or box type used for the shipment.',
    isSystem: true,
  },
];

/** Default enabled flags for first-load seed — common operational fields on by default. */
export const DEFAULT_ENABLED_LABEL_IDS = new Set<string>([
  'label-store-order-number',
  'label-shiplo-order-id',
  'label-tracking-number',
  'label-package-carton-id',
]);

export function seedLabelReferences(): LabelReference[] {
  return SYSTEM_LABEL_REFERENCES.map((ref) => ({
    ...ref,
    enabled: DEFAULT_ENABLED_LABEL_IDS.has(ref.id),
  }));
}
